node('master') {
  stage('Clone Projects') {
    parallel([

      earnings: {

        dir('earnings-regression-test') {

          git(
            url: 'https://github.com/anyTV/earnings.git',
            credentialsId: 'Swaraj'
          )
          sh 'curl https://gist.githubusercontent.com/arnoldamparo/443d1c22e764e77c404d98dc77181b33/raw/c1cdd704654e9de6e31a56a7fb533e23a998ad76/earnings-new.diff | git apply -v'
          sh 'npm install'
          sh 'nohup grunt -f > earnings.log &'
          sh 'nohup node queue_server.js > queue_server.log &'
        }
      },
      earnings_payment_gateway: {

        dir('earnings-payment-gateway') {
          git(
            url: 'https://gitlab.com/anyTV/earnings-payment-gateway.git',
            credentialsId: 'Swaraj_Gitlab'
          )
          sh 'npm install'
          sh 'nohup grunt > earnings-payment-gateway.log &'
        }
      }
    ])
  }

  stage('Test') {
    dir('freedom.cid.testsuite') {
      git(
        url: 'https://gitlab.com/anyTV/qa/freedom.cid.testsuite.git',
        credentialsId: 'Swaraj_Gitlab'
      )
      sh 'curl https://gist.githubusercontent.com/arnoldamparo/b393aaad4a536d0c4a2284705347d2f8/raw/477a70ae6e17d5ce8e017a117b0adcf053dbd929/earnings-automation.diff | git apply -v'
      wrap([$class: 'Xvfb', additionalOptions: '', assignedLabels: '', autoDisplayName: true, debug: true, displayNameOffset: 0, installationName: 'Xvfb', parallelBuild: true, screen: '1024x758x24', timeout: 25]) {
        sh 'echo $DISPLAY'
        sh 'export DISPLAY=:1'
        sh 'mvn -Dtest=EarningsRunner test -Dcucumber.options="--tags @init,@login,@masspay_gen,@terminate"'
      }
    }

  }
}